name: ci-test-go

on:
  push:
    branches: [main]
    paths:
      - "KubeArmor/**"
      - "tests/**"
      - "protobuf/**"
      - ".github/workflows/ci-test-go.yml"
      - "pkg/KubeArmorOperator/**"
  pull_request:
    branches: [main]
    paths:
      - "KubeArmor/**"
      - "tests/**"
      - "protobuf/**"
      - ".github/workflows/ci-test-go.yml"
      - "pkg/KubeArmorOperator/**"
    
# Declare default permissions as read only.
permissions: read-all

jobs:
  go-fmt:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v5
        with:
          go-version-file: 'KubeArmor/go.mod'

      - name: Check gofmt
        run: make gofmt
        working-directory: KubeArmor

  go-lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v5
        with:
          go-version-file: 'KubeArmor/go.mod'

      - name: Run Revive Action on KubeArmor
        uses: morphy2k/revive-action@v2
        with:
          path: "./KubeArmor/..."

  go-lint-tests:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v5
        with:
          go-version-file: 'KubeArmor/go.mod'

      - name: Run Revive Action on KubeArmor tests
        uses: morphy2k/revive-action@v2
        with:
          path: "./tests/..."

  go-sec:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v5
        with:
          go-version-file: 'KubeArmor/go.mod'

      - name: Run Gosec Security Scanner
        run: make gosec
        working-directory: KubeArmor

  go-vuln:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v5
        with:
          go-version-file: 'KubeArmor/go.mod'

      - name: Run govulncheck 
        run: make scan
        working-directory: KubeArmor

  go-test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v5
        with:
          go-version-file: 'KubeArmor/go.mod'

      - name: Run go test on the KubeArmor/KubeArmor directory
        run: go test ./...
        working-directory: KubeArmor

  license:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Check License Header
        uses: apache/skywalking-eyes@3ea9df11bb3a5a85665377d1fd10c02edecf2c40
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
